### ISSUE TITLE
The last 6 characters of the loading message remain after calling `done()`

### ISSUE THREAD

**Issue by llamicron** [0x20F/paris#33]
**Describe the bug**
On Windows, after calling `loading()` and `done()`, 6 characters remain from the loading message. As far as I can tell, it's only the last 6 characters. I haven't tested this on other platforms, as I'm assuming it's a Windows problem. 

**To Reproduce**
Using version `1.5` with default features, this code shows the example. `main.rs`:
```
use std::thread::sleep;
use std::time::Duration;

use paris::Logger;

fn main() {
    let mut log = Logger::new();

    log.loading("Loading");
    sleep(Duration::from_secs(2));
    log.done();
    // "oading" will remain in the terminal
}

```

**Expected behavior**
The entire message to clear

**Screenshots**
While loading, the animation plays but there's a visible `<cyan>` and `</>`. That's another issue though:
https://imgur.com/XORZDVr

After loading stops, this is what remains:
https://imgur.com/zVgEdAj

**Desktop (please complete the following information):**
 - OS: Windows 10
- Tested with Git Bash, CMD, and VSCode integrated terminal

**Comment by llamicron** [comment]
After looking at the source code, I noticed if I change [this line](https://github.com/0x20F/paris/blob/2fe77704f5e7e071b96182b58566146a5e6ed90b/src/logger/mod.rs#L235) to `+ 11` instead of `+5`, it clears everything. I believe that the extra characters are from the visible `<cyan>` tag, as that shouldn't be visible anyway. `<cyan>` is 6 characters, so the amount of characters to clear is 6 more than expected. 

On a related note, what does the `+ 5` represent? It's a bit of a magic number.

**Comment by 0x20F** [comment]
Thanks for the very detailed issue!

The `+5`, if I remember correctly was me having this exact issue and I just threw a number at it and it seemed to work. Was going to fix this but forgot about it. Hehe. The magical `+5` can disappear altogether if `self.loading_message` is set directly to the formatted string that includes the colors, before being passed on to the thread.

I'm pretty sure that would fix it, and clarify the code a bit more. It is late so I might be wrong though. I'll get around to trying it out in the morning. 

## Actually
After looking a bit more at it, it happens because the `<cyan>` never gets formatted, as in, replaced with the color it's supposed to have. This is definitely something that came in with the refactor in 1.5.

**Comment by llamicron** [comment]
Thanks for the quick response.

I just opened a pull request that (sort of) fixes it. I just hardcoded the cyan escape sequence instead of having the formatter do it. Here's the [pull request](https://github.com/0x20F/paris/pull/34). I'm sure there are better ways to fix this, though.

**Comment by 0x20F** [comment]
Did a quick fix in #36 not merging yet since it still feels kind of ugly, but you're welcome to test if the issue is fixed at least.

**Comment by iirelu** [comment]
Why not use "clear entire line" ANSI escape code? ESC[2K

**Comment by 0x20F** [comment]
I did not know this was a thing, should be a lot easier actually!
